"use client";

import { useState } from "react";
import DashboardLayoutWrapper from "@/components/dashboard-layout-wrapper";
import dynamic from "next/dynamic";
import {
  Code2,
  ChevronRight,
  ChevronLeft,
  Copy,
  Check,
  Download,
  PlayCircle,
  Database,
} from "lucide-react";
import Link from "next/link";

const MonacoEditor = dynamic(() => import("@monaco-editor/react"), { ssr: false });

type Framework = "selenium" | "playwright" | "cypress";

const codeSnippets: Record<Framework, { language: string; filename: string; code: string }> = {
  selenium: {
    language: "python",
    filename: "test_login_selenium.py",
    code: `import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# Generated by NextGen QA — Mode B (DOM-Aware)
# Story: US-001 · User Authentication
# Target: https://www.saucedemo.com

STAGING_URL = "https://www.saucedemo.com"


@pytest.fixture
def driver():
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")
    d = webdriver.Chrome(options=options)
    d.implicitly_wait(10)
    yield d
    d.quit()


class TestUserAuthentication:

    def test_successful_login(self, driver):
        """Scenario: Successful login with valid credentials"""
        driver.get(STAGING_URL)
        wait = WebDriverWait(driver, 10)

        # Given I am on the login page
        assert "Swag Labs" in driver.title

        # When I enter valid username
        driver.find_element(By.ID, "user-name").send_keys("standard_user")

        # And I enter valid password
        driver.find_element(By.ID, "password").send_keys("secret_sauce")

        # And I click the login button
        driver.find_element(By.ID, "login-button").click()

        # Then I should be redirected to the products page
        wait.until(EC.url_contains("inventory"))
        assert "inventory" in driver.current_url

    def test_failed_login_invalid_credentials(self, driver):
        """Scenario: Failed login with invalid credentials"""
        driver.get(STAGING_URL)

        driver.find_element(By.ID, "user-name").send_keys("wrong_user")
        driver.find_element(By.ID, "password").send_keys("wrong_pass")
        driver.find_element(By.ID, "login-button").click()

        # Then I should see an error message
        error = driver.find_element(By.CSS_SELECTOR, ".error-message-container")
        assert "Username and password do not match" in error.text
        assert "inventory" not in driver.current_url


class TestShoppingCart:

    def test_add_item_to_cart(self, driver):
        """Scenario: Add item to cart"""
        driver.get(STAGING_URL)
        driver.find_element(By.ID, "user-name").send_keys("standard_user")
        driver.find_element(By.ID, "password").send_keys("secret_sauce")
        driver.find_element(By.ID, "login-button").click()

        driver.find_element(By.ID, "add-to-cart-sauce-labs-backpack").click()

        cart_badge = driver.find_element(By.CLASS_NAME, "shopping_cart_badge")
        assert cart_badge.text == "1"
`,
  },
  playwright: {
    language: "python",
    filename: "test_login_playwright.py",
    code: `import pytest
from playwright.sync_api import sync_playwright, Page, expect

# Generated by NextGen QA — Mode B (DOM-Aware)
# Story: US-001 · User Authentication
# Target: https://www.saucedemo.com

STAGING_URL = "https://www.saucedemo.com"


@pytest.fixture
def page():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        ctx = browser.new_context()
        pg = ctx.new_page()
        yield pg
        browser.close()


class TestUserAuthentication:

    def test_successful_login(self, page: Page):
        """Scenario: Successful login with valid credentials"""
        page.goto(STAGING_URL)

        # Given I am on the login page
        expect(page).to_have_title("Swag Labs")

        # When I enter valid username
        page.fill("#user-name", "standard_user")

        # And I enter valid password
        page.fill("#password", "secret_sauce")

        # And I click the login button
        page.click("#login-button")

        # Then I should be redirected to the products page
        expect(page).to_have_url(f"{STAGING_URL}/inventory.html")

        # Screenshot for the report
        page.screenshot(path="screenshots/login_success.png")

    def test_failed_login_invalid_credentials(self, page: Page):
        """Scenario: Failed login with invalid credentials"""
        page.goto(STAGING_URL)

        page.fill("#user-name", "wrong_user")
        page.fill("#password", "wrong_pass")
        page.click("#login-button")

        # Then I should see an error message
        error = page.locator(".error-message-container")
        expect(error).to_contain_text("Username and password do not match")
        expect(page).not_to_have_url(f"{STAGING_URL}/inventory.html")

        page.screenshot(path="screenshots/login_failure.png")


class TestShoppingCart:

    def test_add_item_to_cart(self, page: Page):
        """Scenario: Add item to cart"""
        page.goto(STAGING_URL)
        page.fill("#user-name", "standard_user")
        page.fill("#password", "secret_sauce")
        page.click("#login-button")

        page.click("#add-to-cart-sauce-labs-backpack")

        expect(page.locator(".shopping_cart_badge")).to_have_text("1")
        expect(page.locator("#add-to-cart-sauce-labs-backpack")).not_to_be_visible()
`,
  },
  cypress: {
    language: "javascript",
    filename: "login.cy.js",
    code: `// Generated by NextGen QA — Mode B (DOM-Aware)
// Story: US-001 · User Authentication
// Target: https://www.saucedemo.com

const STAGING_URL = "https://www.saucedemo.com";

describe("User Authentication", () => {
  beforeEach(() => {
    cy.visit(STAGING_URL);
  });

  it("Successful login with valid credentials", () => {
    // Given I am on the login page
    cy.title().should("eq", "Swag Labs");

    // When I enter valid username
    cy.get("#user-name").type("standard_user");

    // And I enter valid password
    cy.get("#password").type("secret_sauce");

    // And I click the login button
    cy.get("#login-button").click();

    // Then I should be redirected to the products page
    cy.url().should("include", "/inventory");
    cy.screenshot("login_success");
  });

  it("Failed login with invalid credentials", () => {
    cy.get("#user-name").type("wrong_user");
    cy.get("#password").type("wrong_pass");
    cy.get("#login-button").click();

    // Then I should see an error message
    cy.get(".error-message-container")
      .should("be.visible")
      .and("contain", "Username and password do not match");

    cy.url().should("not.include", "/inventory");
    cy.screenshot("login_failure");
  });
});

describe("Shopping Cart", () => {
  beforeEach(() => {
    cy.visit(STAGING_URL);
    cy.get("#user-name").type("standard_user");
    cy.get("#password").type("secret_sauce");
    cy.get("#login-button").click();
  });

  it("Add item to cart", () => {
    cy.get("#add-to-cart-sauce-labs-backpack").click();
    cy.get(".shopping_cart_badge").should("have.text", "1");
    cy.get("#add-to-cart-sauce-labs-backpack").should("not.exist");
    cy.screenshot("cart_add_item");
  });

  it("Remove item from cart", () => {
    cy.get("#add-to-cart-sauce-labs-backpack").click();
    cy.get(".shopping_cart_badge").should("have.text", "1");
    cy.get("#remove-sauce-labs-backpack").click();
    cy.get(".shopping_cart_badge").should("not.exist");
  });
});
`,
  },
};

const frameworkTabs: { id: Framework; label: string; badge: string; color: string }[] = [
  { id: "selenium", label: "Selenium", badge: "Python", color: "text-blue-400" },
  { id: "playwright", label: "Playwright", badge: "Python", color: "text-emerald-400" },
  { id: "cypress", label: "Cypress", badge: "JavaScript", color: "text-amber-400" },
];

const domElements = [
  { selector: "#user-name", tag: "INPUT", step: "fill username" },
  { selector: "#password", tag: "INPUT", step: "fill password" },
  { selector: "#login-button", tag: "INPUT", step: "click login" },
  { selector: ".error-message-container", tag: "H3", step: "check error" },
  { selector: "#add-to-cart-sauce-labs-backpack", tag: "BUTTON", step: "add to cart" },
  { selector: ".shopping_cart_badge", tag: "SPAN", step: "verify cart count" },
];

export default function CodeReviewPage() {
  const [activeFramework, setActiveFramework] = useState<Framework>("playwright");
  const [codeMap, setCodeMap] = useState(codeSnippets);
  const [copied, setCopied] = useState(false);

  const active = codeMap[activeFramework];

  const handleCopy = async () => {
    await navigator.clipboard.writeText(active.code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([active.code], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = active.filename;
    a.click();
  };

  const handleCodeChange = (value: string | undefined) => {
    setCodeMap((prev) => ({
      ...prev,
      [activeFramework]: { ...prev[activeFramework], code: value ?? prev[activeFramework].code },
    }));
  };

  return (
    <DashboardLayoutWrapper>
      {/* Header */}
      <div className="sticky top-0 z-10 bg-slate-950/80 backdrop-blur-sm border-b border-slate-800 px-8 py-5">
        <div className="flex justify-between items-center">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="text-xs font-bold text-purple-400 bg-purple-500/10 border border-purple-500/20 px-2 py-0.5 rounded-full tracking-wider">
                S4
              </span>
              <span className="text-xs text-slate-500">Pipeline Stage 4 of 5</span>
            </div>
            <h1 className="text-2xl font-bold text-white">Code Review</h1>
            <p className="text-slate-400 text-sm mt-0.5">
              Review and edit generated test code · Mode B DOM-Aware · SauceDemo
            </p>
          </div>
          <div className="flex items-center gap-3">
            <Link
              href="/dashboard/mode-setup"
              className="flex items-center gap-2 px-4 py-2 border border-slate-700 text-slate-400 hover:text-white hover:border-slate-600 rounded-lg text-sm transition-all"
            >
              <ChevronLeft className="w-4 h-4" />
              Back
            </Link>
            <Link
              href="/dashboard/execution"
              className="flex items-center gap-2 px-5 py-2 bg-purple-600 hover:bg-purple-500 text-white rounded-lg font-medium text-sm transition-all shadow-lg shadow-purple-600/30"
            >
              <PlayCircle className="w-4 h-4" />
              Run Tests
              <ChevronRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </div>

      <div className="flex gap-5 h-[calc(100vh-145px)] p-6">
        {/* Main Editor Area */}
        <div className="flex-1 flex flex-col min-w-0 rounded-xl border border-slate-700 overflow-hidden">
          {/* Framework Tabs */}
          <div className="flex items-center bg-slate-900 border-b border-slate-700 px-2">
            {frameworkTabs.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveFramework(tab.id)}
                className={`flex items-center gap-2 px-5 py-3 text-sm font-medium border-b-2 transition-all ${
                  activeFramework === tab.id
                    ? "border-purple-500 text-white bg-slate-800/50"
                    : "border-transparent text-slate-500 hover:text-slate-300"
                }`}
              >
                <Code2 className="w-4 h-4" />
                {tab.label}
                <span className={`text-[10px] font-semibold ${tab.color}`}>{tab.badge}</span>
              </button>
            ))}
            <div className="ml-auto flex items-center gap-1 pr-2">
              <button
                onClick={handleCopy}
                className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-white px-2.5 py-1.5 rounded-md hover:bg-slate-700 transition-all"
              >
                {copied ? (
                  <><Check className="w-3.5 h-3.5 text-emerald-400" /> Copied</>
                ) : (
                  <><Copy className="w-3.5 h-3.5" /> Copy</>
                )}
              </button>
              <button
                onClick={handleDownload}
                className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-white px-2.5 py-1.5 rounded-md hover:bg-slate-700 transition-all"
              >
                <Download className="w-3.5 h-3.5" /> Download
              </button>
            </div>
          </div>

          {/* Filename bar */}
          <div className="px-4 py-1.5 bg-slate-900/60 border-b border-slate-700/50 flex items-center gap-2">
            <span className="text-[11px] text-slate-500 font-mono">{active.filename}</span>
            <span className="text-[10px] bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 px-1.5 py-0.5 rounded">
              Mode B · DOM-Aware
            </span>
          </div>

          {/* Monaco */}
          <div className="flex-1">
            <MonacoEditor
              height="100%"
              language={active.language}
              theme="vs-dark"
              value={active.code}
              onChange={handleCodeChange}
              options={{
                fontSize: 12.5,
                lineHeight: 22,
                minimap: { enabled: true },
                wordWrap: "off",
                scrollBeyondLastLine: false,
                padding: { top: 12 },
                fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
                fontLigatures: true,
              }}
            />
          </div>
        </div>

        {/* Right panel — DOM Element Map */}
        <div className="w-64 shrink-0 flex flex-col gap-4">
          <div className="rounded-xl border border-slate-700 overflow-hidden bg-slate-900 flex flex-col">
            <div className="px-4 py-3 border-b border-slate-700 flex items-center gap-2">
              <Database className="w-3.5 h-3.5 text-purple-400" />
              <p className="text-xs font-semibold text-slate-300">DOM Element Map</p>
            </div>
            <div
              className="flex-1 overflow-y-auto py-2"
              style={{ scrollbarWidth: "none" }}
            >
              {domElements.map((el) => (
                <div
                  key={el.selector}
                  className="px-4 py-2.5 hover:bg-slate-800 transition-colors border-b border-slate-800/50 last:border-0"
                >
                  <p className="text-[11px] font-mono text-emerald-400 mb-0.5">{el.selector}</p>
                  <div className="flex items-center justify-between">
                    <span className="text-[10px] text-slate-600 bg-slate-800 px-1.5 py-0.5 rounded font-mono">
                      {el.tag}
                    </span>
                    <span className="text-[10px] text-slate-500">{el.step}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Risk badges */}
          <div className="rounded-xl border border-slate-700 bg-slate-900 p-4">
            <p className="text-xs font-semibold text-slate-400 mb-3 flex items-center gap-2">
              ML Risk Prediction
            </p>
            {[
              { label: "Login Flow", risk: "HIGH", color: "text-red-400 bg-red-500/10 border-red-500/20" },
              { label: "Cart Operations", risk: "MEDIUM", color: "text-amber-400 bg-amber-500/10 border-amber-500/20" },
              { label: "Checkout", risk: "HIGH", color: "text-red-400 bg-red-500/10 border-red-500/20" },
              { label: "Search", risk: "LOW", color: "text-emerald-400 bg-emerald-500/10 border-emerald-500/20" },
            ].map((item) => (
              <div
                key={item.label}
                className="flex items-center justify-between py-2 border-b border-slate-800 last:border-0"
              >
                <span className="text-xs text-slate-300">{item.label}</span>
                <span className={`text-[10px] font-bold px-2 py-0.5 rounded border ${item.color}`}>
                  {item.risk}
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </DashboardLayoutWrapper>
  );
}
